services:
  pg16:
    restart: always
    image: postgres:16.1-alpine3.18
    hostname: mst-pg16
    shm_size: 256mb
    networks:
      - internal
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
    volumes:
      - ./pg16data:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_PASSWORD=langua' # You may replace this password with your one.

  redis:
    restart: always
    image: redis:7.2.3-alpine3.18
    hostname: mst-redis
    networks:
      - internal
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
    volumes:
      - ./redis7data:/data

  esearch:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1-arm64
    hostname: mst-esearch
    environment:
      - "ES_JAVA_OPTS=-Xms3072m -Xmx3072m -Des.enforce.bootstrap.checks=true"
      - "xpack.license.self_generated.type=basic"
      - "xpack.security.enabled=false"
      - "xpack.watcher.enabled=false"
      - "xpack.graph.enabled=false"
      - "xpack.ml.enabled=false"
      - "bootstrap.memory_lock=true"
      - "cluster.name=es-mastodon"
      - "discovery.type=single-node"
      - "thread_pool.write.queue_size=1000"
    networks:
      - internal
    healthcheck:
       test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
    volumes:
      - ./es8data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

  web:
    restart: always
    image: tootsuite/mastodon:v4.2.1
    hostname: mst-web
    env_file: env_settings
    command: bash -c "rm -f /mastodon/tmp/pids/server.pid; bundle exec rails s -p 3000"
    networks:
      - internal
    healthcheck:
      test: ['CMD-SHELL', 'wget -q --spider --proxy=off localhost:3000/health || exit 1']
    depends_on:
      - pg16
      - redis
      - esearch
      - sidekiq
      - streaming
    volumes:
    - ./webroot/system:/mastodon/public/system

  sidekiq:
    restart: always
    image: tootsuite/mastodon:v4.2.1
    hostname: mst-sidekiq
    env_file: env_settings
    command: bundle exec sidekiq
    networks:
      - internal
    healthcheck:
      test: ['CMD-SHELL', "ps aux | grep '[s]idekiq\ 6' || false"]
    depends_on:
      - pg16
      - redis
    volumes:
      - ./webroot/system:/mastodon/public/system

  streaming:
    restart: always
    image: tootsuite/mastodon:v4.2.1
    hostname: mst-streaming
    env_file: env_settings
    command: node ./streaming
    networks:
      - internal
    healthcheck:
      test: ['CMD-SHELL', 'wget -q --spider --proxy=off localhost:4000/api/v1/streaming/health || exit 1']
    depends_on:
      - pg16
      - redis

  nginx:
    image: nginx:1.25.3-alpine
    restart: always
    networks:
      - internal
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./webroot:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - web

networks:
  internal:
